### PR TITLE
Issue #SB-28791 chore: Updated the ubuntu machine in circleci.

### PR DESCRIPTION
**Pull request by AmiableAnil**

### CODE REVIEW

**Review by maheshkumargangula — APPROVED** [review]

**Review by maheshkumargangula — CHANGES_REQUESTED** [review]
Looks like the build failed after this change. Check any other changes we need to do for this.

Is this image has Java 8 by default? Validate this.

**Comment by keshavprasadms** [comment]
Please change this line as below https://github.com/project-sunbird/sunbird-learning-platform/blob/release-4.7.0/.circleci/config.yml#L11
`JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 mvn clean install -DskipTests=true`

**Comment by keshavprasadms** [comment]
Please change these lines as below - https://github.com/project-sunbird/sunbird-learning-platform/blob/release-4.7.0/vmsetup.sh#L6-L7
```
sudo systemctl start elasticsearch
sudo systemctl status elasticsearch --no-pager
```

**Comment by keshavprasadms** [comment]
Also add `JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64` before `mvn` command in https://github.com/project-sunbird/sunbird-learning-platform/blob/release-4.7.0/vmsetup.sh script wherever it occurs.

**Review by maheshkumargangula — APPROVED** [review]

**Pull request merged**
