### PR TITLE
ED-1238 OCI OSS support 

### PR DESCRIPTION
**Pull request by subhashchandrab**
updated cloud-store-sdk to 1.4.6 along with associated class file changes

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Executed jenkins build job Deploy/KnowledgePlatform/Learning

### CODE REVIEW

**Comment by maheshkumargangula** [comment]
@gandham-santhosh - Please review the PR.

**Review by santhosh-tg — CHANGES_REQUESTED** [review]
@subhashchandrab Can we follow the same naming conviction as used for other CSP's please

For ex:
oss_bucket_name: "{{ oci_artifact_oss_bucket_name }}"

change to

oss_bucket_name: "{{ cloud_storage_artifacts_bucketname }}"

**Comment by pallakartheekreddy** [comment]
@subhashchandrab Changes in this PR available in this PR https://github.com/Sunbird-Knowlg/sunbird-learning-platform/pull/1948. Please validate this and close if this is a duplicate.
cc: @maheshkumargangula

**Comment by ddevadat** [comment]
@subhashchandrab close this PR

**Comment by subhashchandrab** [comment]
This PR is not required anymore as a new PR will be created with the right branch information

**Pull request closed without merging**
